# Generated by Django 5.2.3 on 2025-09-12 11:09

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('Phone_number', models.IntegerField()),
                ('department', models.CharField(max_length=50)),
                ('year', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('college', models.CharField(default='Unknown College', max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('img', models.ImageField(blank=True, null=True, upload_to='media/Student_pic/')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_date', models.DateField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('Paid', 'Paid'), ('Pending', 'Pending')], default='Pending', max_length=10)),
                ('reference_id', models.CharField(blank=True, max_length=100, null=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Payment.student')),
            ],
        ),
        migrations.CreateModel(
            name='TransactionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(max_length=100, unique=True)),
                ('transaction_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('method', models.CharField(help_text='e.g. Bkash, Nagad, Bank Transfer', max_length=50)),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='Payment.payment')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Payment.student')),
            ],
        ),
    ]
