# Generated by Django 5.2.3 on 2025-09-12 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherJson',
            fields=[
                ('teacher_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('teacher_name', models.CharField(max_length=100)),
                ('details', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='teacher/')),
            ],
        ),
    ]
