# Generated by Django 5.2.4 on 2025-09-19 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherjson',
            name='password',
            field=models.CharField(default='1234', max_length=128),
        ),
    ]
